services:
  wiki:
    build: .
    pull_policy: build
    networks:
      - ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`chernov.wiki`)"
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.routers.wiki.tls=true"
      - "traefik.http.routers.wiki.tls.certresolver=letsencrypt"

networks:
  ingress:
    external: true
